
BOX_MEMORY=1024

Vagrant.configure(2) do |config|
#  config.vm.box = "ubuntu/xenial64"
  config.vm.box = "ubuntu/bionic64"
  config.vm.synced_folder ".", "/vagrant", disabled: false

  config.vm.provider "virtualbox" do |v|
    v.memory = BOX_MEMORY
    v.cpus = 2
  end

  config.vm.define "box1" do |node|
    node.vm.hostname = "box1"
  end
end

